version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Your_password123
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=sqlserver,1433;Database=frazer_dev;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
volumes:
  sqlserver_data:
