version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: frazer_dev
      POSTGRES_USER: frazer
      POSTGRES_PASSWORD: frazer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=frazer_dev;Username=frazer;Password=frazer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data:
